services:
  postgres:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:7.4.2-alpine
    ports:
      - 6379:6379

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.108.0
    volumes:
      - ./deploy/otel.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 13133:13133 # health_check extension
      - 4318:4318 # OTLP http receiver

  minio:
    image: quay.io/minio/minio:latest
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: 'mc ready local'
      interval: 1s
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniouser
    ports:
      - 9000:9000
      - 9001:9001

  minio-init:
    image: quay.io/minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 miniouser miniouser;
      /usr/bin/mc mb myminio/images;
      /usr/bin/mc anonymous set public myminio/images;
      /usr/bin/mc admin accesskey create myminio --access-key miniokey --secret-key miniokey;
      exit 0;
      "