services:
  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/dashboard.json
    volumes:
      - ./deploy/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ./deploy/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
      - ./deploy/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml:ro

  loki:
     image: grafana/loki:3.0.0
     command: -config.file=/etc/loki/local-config.yaml

  tempo-init:
    image: &tempoImage grafana/tempo:r177-60780f7
    user: root
    entrypoint: "chown 10001:10001 /var/tempo"
    volumes:
      - tempo-volume:/var/tempo

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./deploy/tempo.yml:/etc/tempo.yml
      - tempo-volume:/var/tempo
    depends_on:
      - tempo-init
  
  prometheus:
    image: prom/prometheus:v3.2.1
    command: [ "--web.enable-otlp-receiver", "--config.file=/etc/prometheus.yml" ]
    extra_hosts:
      - "host.docker.internal=host-gateway"
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus.yml
    ports:
      - 9090:9090

# networks:
#   host:
#     driver: 

volumes:
  tempo-volume: