{
 "title": "Postgres",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Postgres Query Latency (90% Percentile)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(default_postgres_query_latency_bucket[$__range])) by (le, label))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Query Latency (90% Percentile)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(default_redis_query_latency_bucket[$__range])) by (le, label))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$__range * rate(default_http_requests_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Errors",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "rate(default_http_requests_errors[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$__range * rate(default_http_requests_latency[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}