global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'shorty'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']

# otlp:
#   promote_resource_attributes:
#     - service.name
#   translation_strategy: NoUTF8EscapingWithSuffixes

# storage:
#   tsdb:
#     out_of_order_time_window: 30m