// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func layout() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><title>Shorty</title><meta charset=\"UTF-8\"><link rel=\"icon\" href=\"/static/favicon.ico\"><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script><script src=\"/static/notify.min.js\"></script></head><body class=\"w-full min-h-full\"><div class=\"absolute top-0 flex flex-row justify-center items-center w-full h-[40px] bg-sky-800 p-1 shadow-xl\"><a href=\"/link\" target=\"_self\" class=\"text-white text-center pl-2 pr-2 h-full hover:bg-sky-700 transition-all\">Link</a><div class=\"border-r ml-2 mr-2 h-full border-white\"></div><a href=\"/image\" target=\"_self\" class=\"text-white text-center pl-2 pr-2 h-full hover:bg-sky-700 transition-all\">Image</a><div class=\"border-r ml-2 mr-2 h-full border-white\"></div><a href=\"/file\" target=\"_self\" class=\"text-white text-center pl-2 pr-2 h-full hover:bg-sky-700 transition-all\">File</a></div><div class=\"absolute top-0 left-2\"><a href=\"/\" target=\"_self\"><div class=\"flex flex-row items-center\"><img src=\"/static/favicon.ico\" class=\"size-6\"><p class=\"font-bold text-white text-3xl ml-2\">Shorty</p></div></a></div><div class=\"absolute right-2 flex flex-row justify-center items-center h-[40px] bg-sky-800 p-1 shadow-xl\"><a href=\"/login\" target=\"_self\" class=\"text-white text-center pl-2 pr-2 h-full hover:bg-sky-700 transition-all\">Login</a></div><div class=\"w-full min-h-full flex justify-center items-center bg-sky-400\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
